# GitHub nf-core repositories that are not pipelines
ignore_repos:
  - .github
  - awsmegatests
  - actions-runners
  - basic_training
  - connectgame
  - configs
  - cookiecutter
  - crossmirna
  - genephylo
  - gh-actions-lint
  - hackathon
  - hackathon-infra
  - logos
  - megatest-seqerakit
  - modules
  - modules-template
  - moleculardynamics
  - nf-core.github.io
  - nft-tiff
  - nft-utils
  - nf-core-utils
  - ops
  - prettier-plugin-nextflow
  - proposals
  - references-assets
  - references-datasheets
  - setup-nextflow
  - setup-nf-test
  - stats
  - strict-syntax-health
  - sublime
  - tandemrepeat
  - test-datasets
  - testpipeline
  - tools
  - tower-action
  - vale
  - vscode-extensionpack
  - website

ignore_topics:
  - nf-core
  - nextflow
  - workflow
  - workflows
  - pipeline
  - pipelines
  - bioinformatics
  - conda
  - containers
  - docker
  - next-generation-sequencing
  - reproducible-research
  - reproducible-science
  - singularity
