repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.2'
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.7.1
          - prettier-plugin-svelte@^2.7.1
          - prettier-plugin-astro@^0.10.0
        args: [--plugin=prettier-plugin-svelte, --plugin=prettier-plugin-astro]
        files: \.(astro|svelte)$
