version: "3.8"
services:
    web:
        image: webdevops/php-apache:7.4
        container_name: web
        restart: always
        environment:
          - WEB_DOCUMENT_ROOT=/var/www/public_html
        volumes:
          - .:/var/www/
        ports:
          - "8888:80"
        command: bash -c "/usr/bin/supervisord"

    npm:
        build: .
        container_name: npm
        volumes:
          - ./public_html/assets/css:/var/www/public_html/assets/css
        command: bash -c "npm run watch-sass"
