[functions]
external_node_modules = ["vscode-oniguruma", "shiki"]
node_bundler = "esbuild"
[build]
environment = { NODE_VERSION = "20.4.0" }
command = "npm run build -w sites/pipelines"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF sites/main-site/src/components sites/pipelines public/pipelines.json"
[[headers]]
for = "/_astro/*"
[headers.values]
Access-Control-Allow-Origin = "*"
