# GitHub nf-core repositories that are not pipelines
ignore_repos:
  - .github
  - awsmegatests
  - actions-runners
  - basic_training
  - configs
  - cookiecutter
  - gh-actions-lint
  - logos
  - modules
  - nf-co.re
  - nf-core.github.io
  - prettier-plugin-nextflow
  - setup-nextflow
  - sublime
  - test-datasets
  - testpipeline
  - tools
  - tower-action
  - vscode-extensionpack
  - website

ignore_topics:
  - nf-core
  - nextflow
  - workflow
  - workflows
  - pipeline
  - pipelines
  - bioinformatics
  - conda
  - containers
  - docker
  - next-generation-sequencing
  - reproducible-research
  - reproducible-science
  - singularity
